### ISSUE TITLE
Make infoPage homepage only list 5 services

### ISSUE THREAD

**Issue by deavmi** [figNET/figNET#13]
And have a link to a list of all services.

**Comment by Walkman100** [comment]
Use #26 to do this if you can :stuck_out_tongue:

**Comment by deavmi** [comment]
I can already do it with the bash page generator I wrote for figWeb.

**Comment by deavmi** [comment]
I have added the code and need to test this: @Walkman100 @Casador

**Comment by deavmi** [comment]
Done. :smile:
