### ISSUE TITLE
Add nodes listing on homepage

### ISSUE THREAD

**Issue by deavmi** [figNET/figNET#14]
And list first 5 nodes and then have a link to a page that lists all nodes on this node.

**Comment by deavmi** [comment]
I have added the code and need to test this: @Walkman100 @Casador

**Comment by deavmi** [comment]
There is a big with this code.

**Comment by deavmi** [comment]
Done :)

**Comment by Walkman100** [comment]
I thought you decided to scrap only 5 and just have them all?

**Comment by deavmi** [comment]
No I didn't. I was going to but I didn't.
